server:
  port: 8080
  compression:
    enabled: true
    excluded-user-agents:
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048

spring:
  profiles:
    active: dev
  datasource:
    dataSourceClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: create-drop
      naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      default_schema: public
naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

swagger:
  title: Celk Spring Angular
  description: REST API
  version: 1.0